server:
  address: localhost
  port: 15000
  
spring:
  main:
    banner-mode: "off" 
  
  jpa:
    open-in-view: false
  
voms:
  tls:
    certificate-path: /etc/grid-security/voms/hostcert.pem
    private-key-path: /etc/grid-security/voms/hostkey.pem
    trust-anchors-dir: /etc/grid-security/certificates
    trust-anchors-refresh-interval-secs: 14400
  aa:
    host: ${server.address}
    port: ${server.port}
    vo-name: test