#
# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2016-2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

spring: 
  flyway:
    locations:
    - classpath:db/migration/h2
    - classpath:db/migration/test

voms:
  tls:
    certificate-path: src/test/resources/certs/voms_example.cert.pem
    private-key-path: src/test/resources/certs/voms_example.key.pem
    trust-anchors-dir: src/test/resources/trust-anchors
    trust-anchors-refresh-interval-secs: 0