spring:
  main:
    banner-mode: "off"
    
  datasource:
    driver-class-name:  org.h2.Driver
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 

  flyway:
    locations:
    - classpath:db/migration/h2
    - classpath:db/migration/test

voms:
  tls:
    