version: "3"

volumes:
  data:
  trustanchors:
  cabundle:

services:
  trust:
    image: indigoiam/trustanchors
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=1
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki
  
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: iam
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: iam

    ports:
      - "3306:3306"
  
  iam-be:
    image: indigoiam/iam-login-service:v1.6.0
    environment: 
      TZ: Europe/Rome
      IAM_JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1044 -Dspring.profiles.active=mysql-test
      IAM_JAR: /code/iam-login-service/target/iam-login-service.war
      IAM_HOST: iam.local.io
      IAM_BASE_URL: https://iam.local.io
      IAM_ISSUER: https://iam.local.io
      IAM_USE_FORWARDED_HEADERS: "true"
      IAM_NOTIFICATION_DISABLE: "true"
      IAM_DB_HOST: db
      IAM_DB_USERNAME: iam
      IAM_DB_PASSWORD: pwd
  
    depends_on:
      - db
    
  iam:
    image: indigoiam/nginx:latest
    container_name: iam

    depends_on: 
      - iam-be
    
    environment:
      TZ: Europe/Rome
      NGINX_HOST: iam
      NGINX_PORT: 443

    ports:
      - "443:443"

    volumes:
      - ./assets/nginx-iam/conf.d:/etc/nginx/conf.d:ro
    
    networks:
      default:
        aliases:
          - iam.local.io

  nginx-voms:
    image: storm2/ngx-voms:latest
    hostname: iam
    dns_search: local.io
    ports:
      - "15000:443"

    depends_on:
      - trust
        # - vomsng

    environment:

      TZ: UTC
      X509_VOMS_DIR: /vomsdir

    volumes:
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/certs:/certs
      - ./assets/vomsdir:/vomsdir
      - ./assets/nginx-voms/nginx.conf:/home/build/local/openresty/nginx/conf/nginx.conf:ro
      - ./assets/nginx-voms/conf.d:/etc/nginx/conf.d:ro
      
  vomsng:
    image: indigoiam/voms-aa:latest
    hostname: vomsng
    environment:
      TZ: Europe/Rome
      IAM_DB_HOST: db
      IAM_DB_USERNAME: iam
      IAM_DB_PASSWORD: pwd
      VOMS_NG_JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1044
    
    ports:
      - "9444:1044"

    depends_on:
      - iam-be

    volumes:
      - ./assets/etc/vomsng:/config:ro
      - ./assets/certs/cert.pem:/etc/grid-security/voms/hostcert.pem:ro
      - ./assets/certs/key.pem:/etc/grid-security/voms/hostkey.pem:ro
      - trustanchors:/etc/grid-security/certificates

  client:
    image: storm2/clients:latest
    environment:
      TZ: Europe/Rome

    depends_on:
      - nginx-voms

    volumes:
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - ./assets/vomsdir:/etc/grid-security/vomsdir
      - ./assets/vomses:/etc/vomses

    entrypoint: sleep infinity
